#!/bin/sh

WORKDATA="/DM/GDAC/WORK/coriolis/"

for mission in `cat coriolis_CHLA.list`
do

	ls -1 ${WORKDATA}${mission}"/profiles/"B*.nc | grep -v D.nc > liste_all_B
 
	R $mission --vanilla < SLOPE_estimation.R

done
